export * as gridGap from "./grid-gap";
export * as overlayerGallery from "./overlayer-gallery";
export * as whitePanel from "./white-panel";
export * as screenPhoto from "./screen-photo";
export * as screenColor from "./screen-color";
export * as paddingContainer from "./padding-container";
export * as veryWhitePanel from "./very-white-panel";
export * as btnInputs from "./btn-inputs";
export * as checkInputs from './check-inputs';
export * as formControlInputs from "./form-control-inputs";
export * as btns from "./btns";
export * as navTopPanel from "./nav-top-panel";
export * as navTopSpace from "./nav-top-space";
export * as navTopItem from "./nav-top-item";
export * as helper from "./helper";
export * as ionIcon from "./ion-icon";
export declare const renderer: {
    "ion-icon": (params: Record<string, string | number>, content: string) => string;
    "nav-top-item": (params: Record<string, string | number>, content: string) => string;
    "nav-top-space": (params: Record<string, string | number>, content: string) => string;
    "nav-top-panel": (params: Record<string, string | number>, content: string) => string;
    "btn-success": (params: Record<string, string | number>, content: string) => string;
    "btn-danger": (params: Record<string, string | number>, content: string) => string;
    "btn-warning": (params: Record<string, string | number>, content: string) => string;
    "btn-info": (params: Record<string, string | number>, content: string) => string;
    "btn-white": (params: Record<string, string | number>, content: string) => string;
    "btn-dark": (params: Record<string, string | number>, content: string) => string;
    "btn-primary": (params: Record<string, string | number>, content: string) => string;
    "btn-secondary": (params: Record<string, string | number>, content: string) => string;
    "text-input": (params: Record<string, string | number>, content: string) => string;
    "number-input": (params: Record<string, string | number>, content: string) => string;
    "date-input": (params: Record<string, string | number>, content: string) => string;
    "email-input": (params: Record<string, string | number>, content: string) => string;
    "file-input": (params: Record<string, string | number>, content: string) => string;
    "image-input": (params: Record<string, string | number>, content: string) => string;
    "month-input": (params: Record<string, string | number>, content: string) => string;
    "password-input": (params: Record<string, string | number>, content: string) => string;
    "randge-input": (params: Record<string, string | number>, content: string) => string;
    "search-input": (params: Record<string, string | number>, content: string) => string;
    "tel-input": (params: Record<string, string | number>, content: string) => string;
    "time-input": (params: Record<string, string | number>, content: string) => string;
    "url-input": (params: Record<string, string | number>, content: string) => string;
    "week-input": (params: Record<string, string | number>, content: string) => string;
    "checkbox-input": (params: Record<string, string | number>, content: string) => string;
    "hidden-input": (params: Record<string, string | number>, content: string) => string;
    "radio-input": (params: Record<string, string | number>, content: string) => string;
    "button-input": (params: Record<string, string | number>, content: string) => string;
    "reset-input": (params: Record<string, string | number>, content: string) => string;
    "submit-input": (params: Record<string, string | number>, content: string) => string;
    "padding-container": (params: Record<string, string | number>, content: string) => string;
    "screen-photo": (params: Record<string, string | number>, content: string) => string;
    "screen-color": (params: Record<string, string | number>, content: string) => string;
    "very-white-panel": (params: Record<string, string | number>, content: string) => string;
    "white-panel": (params: Record<string, string | number>, content: string) => string;
    "overlayer-gallery": (params: Record<string, string | number>, content: string) => string;
    "grid-gap-0": (params: Record<string, string | number>, content: string) => string;
    "grid-gap-5": (params: Record<string, string | number>, content: string) => string;
    "grid-gap-10": (params: Record<string, string | number>, content: string) => string;
    "grid-gap-20": (params: Record<string, string | number>, content: string) => string;
    "grid-gap-30": (params: Record<string, string | number>, content: string) => string;
    object: (params: Record<string, string | number>, content: string) => string;
    big: (params: Record<string, string | number>, content: string) => string;
    link: (params: Record<string, string | number>, content: string) => string;
    small: (params: Record<string, string | number>, content: string) => string;
    strike: (params: Record<string, string | number>, content: string) => string;
    sub: (params: Record<string, string | number>, content: string) => string;
    sup: (params: Record<string, string | number>, content: string) => string;
    map: (params: Record<string, string | number>, content: string) => string;
    input: (params: Record<string, string | number>, content: string) => string;
    code: (params: Record<string, string | number>, content: string) => string;
    data: (params: Record<string, string | number>, content: string) => string;
    progress: (params: Record<string, string | number>, content: string) => string;
    track: (params: Record<string, string | number>, content: string) => string;
    source: (params: Record<string, string | number>, content: string) => string;
    button: (params: Record<string, string | number>, content: string) => string;
    address: (params: Record<string, string | number>, content: string) => string;
    center: (params: Record<string, string | number>, content: string) => string;
    font: (params: Record<string, string | number>, content: string) => string;
    a: (params: Record<string, string | number>, content: string) => string;
    abbr: (params: Record<string, string | number>, content: string) => string;
    area: (params: Record<string, string | number>, content: string) => string;
    article: (params: Record<string, string | number>, content: string) => string;
    aside: (params: Record<string, string | number>, content: string) => string;
    audio: (params: Record<string, string | number>, content: string) => string;
    b: (params: Record<string, string | number>, content: string) => string;
    base: (params: Record<string, string | number>, content: string) => string;
    bdi: (params: Record<string, string | number>, content: string) => string;
    bdo: (params: Record<string, string | number>, content: string) => string;
    blockquote: (params: Record<string, string | number>, content: string) => string;
    body: (params: Record<string, string | number>, content: string) => string;
    br: (params: Record<string, string | number>, content: string) => string;
    canvas: (params: Record<string, string | number>, content: string) => string;
    caption: (params: Record<string, string | number>, content: string) => string;
    cite: (params: Record<string, string | number>, content: string) => string;
    col: (params: Record<string, string | number>, content: string) => string;
    colgroup: (params: Record<string, string | number>, content: string) => string;
    datalist: (params: Record<string, string | number>, content: string) => string;
    dd: (params: Record<string, string | number>, content: string) => string;
    del: (params: Record<string, string | number>, content: string) => string;
    details: (params: Record<string, string | number>, content: string) => string;
    dfn: (params: Record<string, string | number>, content: string) => string;
    dialog: (params: Record<string, string | number>, content: string) => string;
    div: (params: Record<string, string | number>, content: string) => string;
    dl: (params: Record<string, string | number>, content: string) => string;
    dt: (params: Record<string, string | number>, content: string) => string;
    em: (params: Record<string, string | number>, content: string) => string;
    embed: (params: Record<string, string | number>, content: string) => string;
    fieldset: (params: Record<string, string | number>, content: string) => string;
    figcaption: (params: Record<string, string | number>, content: string) => string;
    figure: (params: Record<string, string | number>, content: string) => string;
    footer: (params: Record<string, string | number>, content: string) => string;
    form: (params: Record<string, string | number>, content: string) => string;
    h1: (params: Record<string, string | number>, content: string) => string;
    h2: (params: Record<string, string | number>, content: string) => string;
    h3: (params: Record<string, string | number>, content: string) => string;
    h4: (params: Record<string, string | number>, content: string) => string;
    h5: (params: Record<string, string | number>, content: string) => string;
    h6: (params: Record<string, string | number>, content: string) => string;
    head: (params: Record<string, string | number>, content: string) => string;
    header: (params: Record<string, string | number>, content: string) => string;
    hr: (params: Record<string, string | number>, content: string) => string;
    html: (params: Record<string, string | number>, content: string) => string;
    i: (params: Record<string, string | number>, content: string) => string;
    iframe: (params: Record<string, string | number>, content: string) => string;
    img: (params: Record<string, string | number>, content: string) => string;
    ins: (params: Record<string, string | number>, content: string) => string;
    kbd: (params: Record<string, string | number>, content: string) => string;
    label: (params: Record<string, string | number>, content: string) => string;
    li: (params: Record<string, string | number>, content: string) => string;
    main: (params: Record<string, string | number>, content: string) => string;
    mark: (params: Record<string, string | number>, content: string) => string;
    meta: (params: Record<string, string | number>, content: string) => string;
    meter: (params: Record<string, string | number>, content: string) => string;
    nav: (params: Record<string, string | number>, content: string) => string;
    noscript: (params: Record<string, string | number>, content: string) => string;
    ol: (params: Record<string, string | number>, content: string) => string;
    optgroup: (params: Record<string, string | number>, content: string) => string;
    option: (params: Record<string, string | number>, content: string) => string;
    output: (params: Record<string, string | number>, content: string) => string;
    p: (params: Record<string, string | number>, content: string) => string;
    picture: (params: Record<string, string | number>, content: string) => string;
    pre: (params: Record<string, string | number>, content: string) => string;
    q: (params: Record<string, string | number>, content: string) => string;
    rp: (params: Record<string, string | number>, content: string) => string;
    rt: (params: Record<string, string | number>, content: string) => string;
    ruby: (params: Record<string, string | number>, content: string) => string;
    s: (params: Record<string, string | number>, content: string) => string;
    samp: (params: Record<string, string | number>, content: string) => string;
    script: (params: Record<string, string | number>, content: string) => string;
    section: (params: Record<string, string | number>, content: string) => string;
    select: (params: Record<string, string | number>, content: string) => string;
    span: (params: Record<string, string | number>, content: string) => string;
    strong: (params: Record<string, string | number>, content: string) => string;
    style: (params: Record<string, string | number>, content: string) => string;
    summary: (params: Record<string, string | number>, content: string) => string;
    table: (params: Record<string, string | number>, content: string) => string;
    tbody: (params: Record<string, string | number>, content: string) => string;
    td: (params: Record<string, string | number>, content: string) => string;
    template: (params: Record<string, string | number>, content: string) => string;
    textarea: (params: Record<string, string | number>, content: string) => string;
    tfoot: (params: Record<string, string | number>, content: string) => string;
    th: (params: Record<string, string | number>, content: string) => string;
    thead: (params: Record<string, string | number>, content: string) => string;
    time: (params: Record<string, string | number>, content: string) => string;
    title: (params: Record<string, string | number>, content: string) => string;
    tr: (params: Record<string, string | number>, content: string) => string;
    u: (params: Record<string, string | number>, content: string) => string;
    ul: (params: Record<string, string | number>, content: string) => string;
    var: (params: Record<string, string | number>, content: string) => string;
    video: (params: Record<string, string | number>, content: string) => string;
    wbr: (params: Record<string, string | number>, content: string) => string;
    acronym: (params: Record<string, string | number>, content: string) => string;
    applet: (params: Record<string, string | number>, content: string) => string;
    basefont: (params: Record<string, string | number>, content: string) => string;
    dir: (params: Record<string, string | number>, content: string) => string;
    frame: (params: Record<string, string | number>, content: string) => string;
    frameset: (params: Record<string, string | number>, content: string) => string;
    keygen: (params: Record<string, string | number>, content: string) => string;
    noframes: (params: Record<string, string | number>, content: string) => string;
    param: (params: Record<string, string | number>, content: string) => string;
    tt: (params: Record<string, string | number>, content: string) => string;
    svg: (params: Record<string, string | number>, content: string) => string;
    "!DOCTYPE": (params: Record<string, string | number>, content: string) => string;
    command: (params: Record<string, string | number>, content: string) => string;
};
