export * as gridGap from "./grid-gap";
export * as overlayerGallery from "./overlayer-gallery";
export * as whitePanel from "./white-panel";
export * as screenPhoto from "./screen-photo";
export * as screenColor from "./screen-color";
export * as paddingContainer from "./padding-container";
export * as veryWhitePanel from "./very-white-panel";
export * as btnInputs from "./btn-inputs";
export * as checkInputs from './check-inputs';
export * as formControlInputs from "./form-control-inputs";
export * as btns from "./btns";
export * as navTopPanel from "./nav-top-panel";
export * as navTopSpace from "./nav-top-space";
export * as navTopItem from "./nav-top-item";
export * as helper from "./helper";
export * as ionIcon from "./ion-icon";
export declare const renderer: {
    readonly "ion-icon": (params: Record<string, string | number>, content: string) => string;
    readonly "nav-top-item": (params: Record<string, string | number>, content: string) => string;
    readonly "nav-top-space": (params: Record<string, string | number>, content: string) => string;
    readonly "nav-top-panel": (params: Record<string, string | number>, content: string) => string;
    readonly "btn-success": (params: Record<string, string | number>, content: string) => string;
    readonly "btn-danger": (params: Record<string, string | number>, content: string) => string;
    readonly "btn-warning": (params: Record<string, string | number>, content: string) => string;
    readonly "btn-info": (params: Record<string, string | number>, content: string) => string;
    readonly "btn-white": (params: Record<string, string | number>, content: string) => string;
    readonly "btn-dark": (params: Record<string, string | number>, content: string) => string;
    readonly "btn-primary": (params: Record<string, string | number>, content: string) => string;
    readonly "btn-secondary": (params: Record<string, string | number>, content: string) => string;
    readonly "text-input": (params: Record<string, string | number>, content: string) => string;
    readonly "number-input": (params: Record<string, string | number>, content: string) => string;
    readonly "date-input": (params: Record<string, string | number>, content: string) => string;
    readonly "email-input": (params: Record<string, string | number>, content: string) => string;
    readonly "file-input": (params: Record<string, string | number>, content: string) => string;
    readonly "image-input": (params: Record<string, string | number>, content: string) => string;
    readonly "month-input": (params: Record<string, string | number>, content: string) => string;
    readonly "password-input": (params: Record<string, string | number>, content: string) => string;
    readonly "randge-input": (params: Record<string, string | number>, content: string) => string;
    readonly "search-input": (params: Record<string, string | number>, content: string) => string;
    readonly "tel-input": (params: Record<string, string | number>, content: string) => string;
    readonly "time-input": (params: Record<string, string | number>, content: string) => string;
    readonly "url-input": (params: Record<string, string | number>, content: string) => string;
    readonly "week-input": (params: Record<string, string | number>, content: string) => string;
    readonly "checkbox-input": (params: Record<string, string | number>, content: string) => string;
    readonly "hidden-input": (params: Record<string, string | number>, content: string) => string;
    readonly "radio-input": (params: Record<string, string | number>, content: string) => string;
    readonly "button-input": (params: Record<string, string | number>, content: string) => string;
    readonly "reset-input": (params: Record<string, string | number>, content: string) => string;
    readonly "submit-input": (params: Record<string, string | number>, content: string) => string;
    readonly "padding-container": (params: Record<string, string | number>, content: string) => string;
    readonly "screen-photo": (params: Record<string, string | number>, content: string) => string;
    readonly "screen-color": (params: Record<string, string | number>, content: string) => string;
    readonly "very-white-panel": (params: Record<string, string | number>, content: string) => string;
    readonly "white-panel": (params: Record<string, string | number>, content: string) => string;
    readonly "overlayer-gallery": (params: Record<string, string | number>, content: string) => string;
    readonly "grid-gap-0": (params: Record<string, string | number>, content: string) => string;
    readonly "grid-gap-5": (params: Record<string, string | number>, content: string) => string;
    readonly "grid-gap-10": (params: Record<string, string | number>, content: string) => string;
    readonly "grid-gap-20": (params: Record<string, string | number>, content: string) => string;
    readonly "grid-gap-30": (params: Record<string, string | number>, content: string) => string;
    readonly object: (params: Record<string, string | number>, content: string) => string;
    readonly big: (params: Record<string, string | number>, content: string) => string;
    readonly link: (params: Record<string, string | number>, content: string) => string;
    readonly small: (params: Record<string, string | number>, content: string) => string;
    readonly strike: (params: Record<string, string | number>, content: string) => string;
    readonly sub: (params: Record<string, string | number>, content: string) => string;
    readonly sup: (params: Record<string, string | number>, content: string) => string;
    readonly map: (params: Record<string, string | number>, content: string) => string;
    readonly input: (params: Record<string, string | number>, content: string) => string;
    readonly code: (params: Record<string, string | number>, content: string) => string;
    readonly data: (params: Record<string, string | number>, content: string) => string;
    readonly progress: (params: Record<string, string | number>, content: string) => string;
    readonly track: (params: Record<string, string | number>, content: string) => string;
    readonly source: (params: Record<string, string | number>, content: string) => string;
    readonly button: (params: Record<string, string | number>, content: string) => string;
    readonly address: (params: Record<string, string | number>, content: string) => string;
    readonly center: (params: Record<string, string | number>, content: string) => string;
    readonly font: (params: Record<string, string | number>, content: string) => string;
    readonly a: (params: Record<string, string | number>, content: string) => string;
    readonly abbr: (params: Record<string, string | number>, content: string) => string;
    readonly area: (params: Record<string, string | number>, content: string) => string;
    readonly article: (params: Record<string, string | number>, content: string) => string;
    readonly aside: (params: Record<string, string | number>, content: string) => string;
    readonly audio: (params: Record<string, string | number>, content: string) => string;
    readonly b: (params: Record<string, string | number>, content: string) => string;
    readonly base: (params: Record<string, string | number>, content: string) => string;
    readonly bdi: (params: Record<string, string | number>, content: string) => string;
    readonly bdo: (params: Record<string, string | number>, content: string) => string;
    readonly blockquote: (params: Record<string, string | number>, content: string) => string;
    readonly body: (params: Record<string, string | number>, content: string) => string;
    readonly br: (params: Record<string, string | number>, content: string) => string;
    readonly canvas: (params: Record<string, string | number>, content: string) => string;
    readonly caption: (params: Record<string, string | number>, content: string) => string;
    readonly cite: (params: Record<string, string | number>, content: string) => string;
    readonly col: (params: Record<string, string | number>, content: string) => string;
    readonly colgroup: (params: Record<string, string | number>, content: string) => string;
    readonly datalist: (params: Record<string, string | number>, content: string) => string;
    readonly dd: (params: Record<string, string | number>, content: string) => string;
    readonly del: (params: Record<string, string | number>, content: string) => string;
    readonly details: (params: Record<string, string | number>, content: string) => string;
    readonly dfn: (params: Record<string, string | number>, content: string) => string;
    readonly dialog: (params: Record<string, string | number>, content: string) => string;
    readonly div: (params: Record<string, string | number>, content: string) => string;
    readonly dl: (params: Record<string, string | number>, content: string) => string;
    readonly dt: (params: Record<string, string | number>, content: string) => string;
    readonly em: (params: Record<string, string | number>, content: string) => string;
    readonly embed: (params: Record<string, string | number>, content: string) => string;
    readonly fieldset: (params: Record<string, string | number>, content: string) => string;
    readonly figcaption: (params: Record<string, string | number>, content: string) => string;
    readonly figure: (params: Record<string, string | number>, content: string) => string;
    readonly footer: (params: Record<string, string | number>, content: string) => string;
    readonly form: (params: Record<string, string | number>, content: string) => string;
    readonly h1: (params: Record<string, string | number>, content: string) => string;
    readonly h2: (params: Record<string, string | number>, content: string) => string;
    readonly h3: (params: Record<string, string | number>, content: string) => string;
    readonly h4: (params: Record<string, string | number>, content: string) => string;
    readonly h5: (params: Record<string, string | number>, content: string) => string;
    readonly h6: (params: Record<string, string | number>, content: string) => string;
    readonly head: (params: Record<string, string | number>, content: string) => string;
    readonly header: (params: Record<string, string | number>, content: string) => string;
    readonly hr: (params: Record<string, string | number>, content: string) => string;
    readonly html: (params: Record<string, string | number>, content: string) => string;
    readonly i: (params: Record<string, string | number>, content: string) => string;
    readonly iframe: (params: Record<string, string | number>, content: string) => string;
    readonly img: (params: Record<string, string | number>, content: string) => string;
    readonly ins: (params: Record<string, string | number>, content: string) => string;
    readonly kbd: (params: Record<string, string | number>, content: string) => string;
    readonly label: (params: Record<string, string | number>, content: string) => string;
    readonly li: (params: Record<string, string | number>, content: string) => string;
    readonly main: (params: Record<string, string | number>, content: string) => string;
    readonly mark: (params: Record<string, string | number>, content: string) => string;
    readonly meta: (params: Record<string, string | number>, content: string) => string;
    readonly meter: (params: Record<string, string | number>, content: string) => string;
    readonly nav: (params: Record<string, string | number>, content: string) => string;
    readonly noscript: (params: Record<string, string | number>, content: string) => string;
    readonly ol: (params: Record<string, string | number>, content: string) => string;
    readonly optgroup: (params: Record<string, string | number>, content: string) => string;
    readonly option: (params: Record<string, string | number>, content: string) => string;
    readonly output: (params: Record<string, string | number>, content: string) => string;
    readonly p: (params: Record<string, string | number>, content: string) => string;
    readonly picture: (params: Record<string, string | number>, content: string) => string;
    readonly pre: (params: Record<string, string | number>, content: string) => string;
    readonly q: (params: Record<string, string | number>, content: string) => string;
    readonly rp: (params: Record<string, string | number>, content: string) => string;
    readonly rt: (params: Record<string, string | number>, content: string) => string;
    readonly ruby: (params: Record<string, string | number>, content: string) => string;
    readonly s: (params: Record<string, string | number>, content: string) => string;
    readonly samp: (params: Record<string, string | number>, content: string) => string;
    readonly script: (params: Record<string, string | number>, content: string) => string;
    readonly section: (params: Record<string, string | number>, content: string) => string;
    readonly select: (params: Record<string, string | number>, content: string) => string;
    readonly span: (params: Record<string, string | number>, content: string) => string;
    readonly strong: (params: Record<string, string | number>, content: string) => string;
    readonly style: (params: Record<string, string | number>, content: string) => string;
    readonly summary: (params: Record<string, string | number>, content: string) => string;
    readonly table: (params: Record<string, string | number>, content: string) => string;
    readonly tbody: (params: Record<string, string | number>, content: string) => string;
    readonly td: (params: Record<string, string | number>, content: string) => string;
    readonly template: (params: Record<string, string | number>, content: string) => string;
    readonly textarea: (params: Record<string, string | number>, content: string) => string;
    readonly tfoot: (params: Record<string, string | number>, content: string) => string;
    readonly th: (params: Record<string, string | number>, content: string) => string;
    readonly thead: (params: Record<string, string | number>, content: string) => string;
    readonly time: (params: Record<string, string | number>, content: string) => string;
    readonly title: (params: Record<string, string | number>, content: string) => string;
    readonly tr: (params: Record<string, string | number>, content: string) => string;
    readonly u: (params: Record<string, string | number>, content: string) => string;
    readonly ul: (params: Record<string, string | number>, content: string) => string;
    readonly var: (params: Record<string, string | number>, content: string) => string;
    readonly video: (params: Record<string, string | number>, content: string) => string;
    readonly wbr: (params: Record<string, string | number>, content: string) => string;
    readonly acronym: (params: Record<string, string | number>, content: string) => string;
    readonly applet: (params: Record<string, string | number>, content: string) => string;
    readonly basefont: (params: Record<string, string | number>, content: string) => string;
    readonly dir: (params: Record<string, string | number>, content: string) => string;
    readonly frame: (params: Record<string, string | number>, content: string) => string;
    readonly frameset: (params: Record<string, string | number>, content: string) => string;
    readonly keygen: (params: Record<string, string | number>, content: string) => string;
    readonly noframes: (params: Record<string, string | number>, content: string) => string;
    readonly param: (params: Record<string, string | number>, content: string) => string;
    readonly tt: (params: Record<string, string | number>, content: string) => string;
    readonly svg: (params: Record<string, string | number>, content: string) => string;
    readonly "!DOCTYPE": (params: Record<string, string | number>, content: string) => string;
    readonly command: (params: Record<string, string | number>, content: string) => string;
};
export type T = keyof typeof renderer;
